version: '3.6'

services:
    ui:
        volumes:
            - static:/home/node/app/build:rw
        command: yarn build
    proxy:
        container_name: dojo-server
        build: ./live
        volumes:
            - ./live/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - static:/usr/share/nginx/html:ro
        depends_on:
            - ui
            - api
        ports:
            - 80:8080

volumes:
    static:
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: uid=1000
