version: '3.6'

services:
    ui:
        container_name: dojo-ui
        build: ./client
        volumes:
            - ./client:/home/node/app
    api:
        container_name: dojo-api
        build: ./server
        environment:
            - FLASK_APP=/home/python/app/dojo
        volumes:
            - ./server:/home/python/app
        depends_on:
            - db
    db:
        container_name: dojo-db
        image: postgres:10.4-alpine
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
