version: '3.6'

services:
    ui:
        env_file:
            - ./client/.env.live
        volumes:
            - static:/home/node/app/build:rw
        command: yarn build
    api:
        env_file:
            - ./server/.env.live
        entrypoint: /init.sh
        command: /wsgi.sh
    db:
        volumes:
            - ~/.pgdata/dojo-live:/var/lib/postgresql/data/pgdata
    proxy:
        container_name: dojo-server
        build: ./live
        env_file:
            - ./live/.env
        volumes:
            - ./live/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./live/etc/nginx/api.conf:/etc/nginx/api.conf:ro
            - static:/usr/share/nginx/html:ro
        depends_on:
            - ui
            - api
        ports:
            - 80:8080

volumes:
    static:
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: uid=1000
