"""empty message

Revision ID: 8bfb5e2e01a9
Revises: 
Create Date: 2018-07-09 13:46:57.748546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8bfb5e2e01a9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    # Organizations
    op.create_table(
        "organizations",
        sa.Column(
            "id",
            postgresql.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("import_id", sa.Integer(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("handle", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_import_id"), "organizations", ["import_id"], unique=False
    )
    # Users
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("import_id", sa.Integer(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("profile_url", sa.String(), nullable=True),
        sa.Column("handle", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_import_id"), "users", ["import_id"], unique=False)
    # Organizations <-> Users
    op.create_table(
        "user_organization_mappings",
        sa.Column("user_id", postgresql.UUID(), nullable=False),
        sa.Column("org_id", postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("user_id", "org_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_organization_mappings")
    op.drop_index(op.f("ix_users_import_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_import_id"), table_name="organizations")
    op.drop_table("organizations")
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp"')
    # ### end Alembic commands ###
